#include "legacy_compat.h"

static BulletTypeClass const ClassSniper(BULLET_BULLET,
                                        "50cal",
                                        false,
                                        false,
                                        false,
                                        false,
                                        true,
                                        false,
                                        false,
                                        false,
                                        true,
                                        false,
                                        false,
                                        false,
                                        0,
                                        0,
                                        MPH_LIGHT_SPEED,
                                        0,
                                        WARHEAD_HOLLOW_POINT,
                                        ANIM_PIFF);

static BulletTypeClass const ClassBullet(BULLET_BULLET,
                                        "50cal",
                                        false,
                                        false,
                                        false,
                                        false,
                                        true,
                                        false,
                                        false,
                                        false,
                                        true,
                                        false,
                                        false,
                                        false,
                                        0,
                                        0,
                                        MPH_LIGHT_SPEED,
                                        0,
                                        WARHEAD_SA,
                                        ANIM_PIFF);

static BulletTypeClass const ClassSpreadfire(BULLET_SPREADFIRE,
                                            "50cal",
                                            true,
                                            false,
                                            false,
                                            false,
                                            true,
                                            false,
                                            false,
                                            false,
                                            true,
                                            false,
                                            false,
                                            false,
                                            0,
                                            0,
                                            MPH_LIGHT_SPEED,
                                            0,
                                            WARHEAD_HE,
                                            ANIM_PIFFPIFF);

static BulletTypeClass const ClassAPDS(BULLET_APDS,
                                      "120mm",
                                      false,
                                      false,
                                      false,
                                      false,
                                      false,
                                      false,
                                      false,
                                      false,
                                      true,
                                      false,
                                      false,
                                      false,
                                      0,
                                      0,
                                      MPH_VERY_FAST,
                                      0,
                                      WARHEAD_AP,
                                      ANIM_VEH_HIT3);

static BulletTypeClass const Class120mm(BULLET_HE,
                                       "120mm",
                                       true,
                                       false,
                                       true,
                                       false,
                                       false,
                                       false,
                                       false,
                                       false,
                                       true,
                                       true,
                                       false,
                                       false,
                                       0,
                                       0,
                                       MPH_MEDIUM_FAST,
                                       0,
                                       WARHEAD_HE,
                                       ANIM_ART_EXP1);

static BulletTypeClass const ClassMissile(BULLET_SSM,
                                         "DRAGON",
                                         true,
                                         true,
                                         false,
                                         false,
                                         false,
                                         true,
                                         true,
                                         true,
                                         false,
                                         true,
                                         true,
                                         true,
                                         7,
                                         0,
                                         MPH_ROCKET,
                                         5,
                                         WARHEAD_HE,
                                         ANIM_FRAG1);

static BulletTypeClass const ClassMissile2(BULLET_SSM2,
                                          "DRAGON",
                                          true,
                                          true,
                                          false,
                                          false,
                                          false,
                                          true,
                                          true,
                                          true,
                                          false,
                                          true,
                                          true,
                                          true,
                                          9,
                                          0,
                                          MPH_ROCKET,
                                          5,
                                          WARHEAD_HE,
                                          ANIM_FRAG1);

static BulletTypeClass const ClassPatriot(BULLET_SAM,
                                         "NIKE",
                                         true,
                                         true,
                                         false,
                                         false,
                                         false,
                                         true,
                                         true,
                                         true,
                                         false,
                                         true,
                                         true,
                                         true,
                                         7,
                                         0,
                                         MPH_VERY_FAST,
                                         6,
                                         WARHEAD_HE,
                                         ANIM_VEH_HIT1);

static BulletTypeClass const ClassDragon(BULLET_TOW,
                                        "DRAGON",
                                        true,
                                        true,
                                        false,
                                        false,
                                        false,
                                        true,
                                        true,
                                        true,
                                        false,
                                        true,
                                        true,
                                        false,
                                        6,
                                        0,
                                        MPH_ROCKET,
                                        6,
                                        WARHEAD_AP,
                                        ANIM_VEH_HIT2);

static BulletTypeClass const ClassFlame(BULLET_FLAME,
                                       "FLAME",
                                       true,
                                       false,
                                       false,
                                       false,
                                       true,
                                       false,
                                       true,
                                       false,
                                       true,
                                       false,
                                       true,
                                       false,
                                       0,
                                       0,
                                       MPH_FAST,
                                       0,
                                       WARHEAD_FIRE,
                                       ANIM_NONE);

static BulletTypeClass const ClassChem(BULLET_CHEMSPRAY,
                                      "CHEM",
                                      true,
                                      false,
                                      false,
                                      false,
                                      true,
                                      false,
                                      false,
                                      false,
                                      true,
                                      false,
                                      true,
                                      false,
                                      0,
                                      0,
                                      MPH_FAST,
                                      0,
                                      WARHEAD_HE,
                                      ANIM_NONE);

static BulletTypeClass const ClassNapalm(BULLET_NAPALM,
                                        "NAPALM",
                                        true,
                                        false,
                                        true,
                                        true,
                                        false,
                                        false,
                                        true,
                                        false,
                                        true,
                                        false,
                                        true,
                                        false,
                                        0,
                                        0,
                                        MPH_MEDIUM_SLOW,
                                        0,
                                        WARHEAD_FIRE,
                                        ANIM_NAPALM2);

static BulletTypeClass const ClassGrenade(BULLET_GRENADE,
                                         "GRENADE",
                                         true,
                                         false,
                                         true,
                                         false,
                                         false,
                                         false,
                                         false,
                                         false,
                                         true,
                                         true,
                                         false,
                                         false,
                                         0,
                                         0,
                                         MPH_MEDIUM_SLOW,
                                         0,
                                         WARHEAD_HE,
                                         ANIM_VEH_HIT2);

static BulletTypeClass const ClassLaser(BULLET_LASER,
                                       "LASER",
                                       false,
                                       false,
                                       false,
                                       false,
                                       true,
                                       false,
                                       false,
                                       false,
                                       true,
                                       false,
                                       false,
                                       false,
                                       0,
                                       0,
                                       MPH_LIGHT_SPEED,
                                       0,
                                       WARHEAD_LASER,
                                       ANIM_NONE);

static BulletTypeClass const ClassNukeUp(BULLET_NUKE_UP,
                                        "NUKE",
                                        true,
                                        false,
                                        false,
                                        false,
                                        false,
                                        false,
                                        true,
                                        true,
                                        true,
                                        true,
                                        true,
                                        false,
                                        0,
                                        0,
                                        MPH_VERY_FAST,
                                        5,
                                        WARHEAD_HE,
                                        ANIM_FRAG1);

static BulletTypeClass const ClassNukeDown(BULLET_NUKE_DOWN,
                                          "NUKE",
                                          true,
                                          false,
                                          false,
                                          false,
                                          false,
                                          false,
                                          true,
                                          true,
                                          true,
                                          true,
                                          true,
                                          false,
                                          0,
                                          0,
                                          MPH_VERY_FAST,
                                          0,
                                          WARHEAD_HE,
                                          ANIM_ATOM_BLAST);

static BulletTypeClass const ClassHonestJohn(BULLET_HONEST_JOHN,
                                            "NAPALM",
                                            true,
                                            true,
                                            false,
                                            false,
                                            false,
                                            true,
                                            true,
                                            true,
                                            false,
                                            true,
                                            true,
                                            true,
                                            7,
                                            0,
                                            MPH_FAST,
                                            6,
                                            WARHEAD_FIRE,
                                            ANIM_NAPALM3);

static BulletTypeClass const ClassHeadButt(BULLET_HEADBUTT,
                                          "BUTT",
                                          false,
                                          false,
                                          false,
                                          false,
                                          true,
                                          false,
                                          false,
                                          false,
                                          true,
                                          false,
                                          false,
                                          false,
                                          0,
                                          0,
                                          MPH_LIGHT_SPEED,
                                          0,
                                          WARHEAD_HEADBUTT,
                                          ANIM_NONE);

static BulletTypeClass const ClassTRexBite(BULLET_TREXBITE,
                                         "CHEW",
                                         false,
                                         false,
                                         false,
                                         false,
                                         true,
                                         false,
                                         false,
                                         false,
                                         true,
                                         false,
                                         false,
                                         false,
                                         0,
                                         0,
                                         MPH_LIGHT_SPEED,
                                         0,
                                         WARHEAD_FEEDME,
                                         ANIM_NONE);

BulletTypeClass const* const BulletTypeClass::Pointers[BULLET_COUNT] = {
    &ClassSniper,      // BULLET_SNIPER
    &ClassBullet,      // BULLET_BULLET
    &ClassAPDS,        // BULLET_APDS
    &Class120mm,       // BULLET_HE
    &ClassMissile,     // BULLET_SSM
    &ClassMissile2,    // BULLET_SSM2
    &ClassPatriot,     // BULLET_SAM
    &ClassDragon,      // BULLET_TOW
    &ClassFlame,       // BULLET_FLAME
    &ClassChem,        // BULLET_CHEMSPRAY
    &ClassNapalm,      // BULLET_NAPALM
    &ClassGrenade,     // BULLET_GRENADE
    &ClassLaser,       // BULLET_LASER
    &ClassNukeUp,      // BULLET_NUKE_UP
    &ClassNukeDown,    // BULLET_NUKE_DOWN
    &ClassHonestJohn,  // BULLET_HONEST_JOHN
    &ClassSpreadfire,  // BULLET_SPREADFIRE
    &ClassHeadButt,    // BULLET_HEADBUTT
    &ClassTRexBite,    // BULLET_TREXBITE
};

BulletTypeClass::BulletTypeClass(BulletType type,
                                 char const* ininame,
                                 bool is_high,
                                 bool is_homing,
                                 bool is_arcing,
                                 bool is_dropping,
                                 bool is_invisible,
                                 bool is_proximity_armed,
                                 bool is_flame_equipped,
                                 bool is_fueled,
                                 bool is_faceless,
                                 bool is_inaccurate,
                                 bool is_translucent,
                                 bool is_antiaircraft,
                                 int arming,
                                 int range,
                                 MPHType maxspeed,
                                 unsigned rot,
                                 WarheadType warhead,
                                 AnimType explosion)
    : ObjectTypeClass(true, false, false, true, false, false, true, true, TXT_NONE, ininame, ARMOR_NONE, 0),
      Type(type),
      Warhead(warhead),
      Explosion(explosion),
      MaxSpeed(maxspeed),
      ROT(rot),
      Arming(arming),
      Range(range),
      IsHigh(is_high ? 1U : 0U),
      IsHoming(is_homing ? 1U : 0U),
      IsArcing(is_arcing ? 1U : 0U),
      IsDropping(is_dropping ? 1U : 0U),
      IsInvisible(is_invisible ? 1U : 0U),
      IsProximityArmed(is_proximity_armed ? 1U : 0U),
      IsFlameEquipped(is_flame_equipped ? 1U : 0U),
      IsFueled(is_fueled ? 1U : 0U),
      IsFaceless(is_faceless ? 1U : 0U),
      IsInaccurate(is_inaccurate ? 1U : 0U),
      IsTranslucent(is_translucent ? 1U : 0U),
      IsAntiAircraft(is_antiaircraft ? 1U : 0U) {}

void BulletTypeClass::One_Time(void) {
    for (int i = BULLET_FIRST; i < BULLET_COUNT; ++i) {
        BulletType index = static_cast<BulletType>(i);
        BulletTypeClass const& bullet = As_Reference(index);
        char fullname[_MAX_FNAME + _MAX_EXT];

        if (!bullet.IsInvisible) {
            _makepath(fullname, NULL, NULL, bullet.IniName, ".SHP");

            RawFileClass file(fullname);

            if (file.Is_Available()) {
                (const_cast<void const*&>(bullet.ImageData)) = Load_Alloc_Data(file);
            } else {
                (const_cast<void const*&>(bullet.ImageData)) = MixFileClass::Retrieve(fullname);
            }
        }
    }
}

